### ISSUE TITLE
HDMI

### ISSUE THREAD

**Issue by dm5n** [Baio1977/DELL-Inspiron-5584#1]
Thanks for your guide. I've modified your EFI and used to install Big Sur on Dell 7580 with specs:
 
CPU: Intel Core i7-8565U
GPU: NVIDIA GeForce MX150 (2GB GDDR5) and Intel UHD 620
Display: 15.6”, Full HD (1920 x 1080), IPS
Storage: 1tb SSD (macOS) and 512 NVMe  (WIn 10)
RAM: 16GB DDR4, 2400 MHz

I haven't got Intel UHD 620 iGPU HDMI Output working. Any advice please?

**Comment by Baio1977** [comment]
My EFI patch is for my DELL with 1 HDMI video output only, so I set N2 Video Outputs the 3rd port I disabled it, you should check and enable it

![Schermata 2021-01-08 alle 16 27 12](https://user-images.githubusercontent.com/59058746/104032371-5ff5f700-51ce-11eb-8fa5-9a2fc112d8d1.png)
