### ISSUE TITLE
Will the EFI work on Dell Inspiron 5480?

### ISSUE THREAD

**Issue by bournesup** [Baio1977/DELL-Inspiron-5584#5]
Dell Inspiron 5480 has a very similar hardware configuration. Will the EFI be suitable as well? Thanks.

**Comment by Baio1977** [comment]
Try it otherwise I can help you create one

**Comment by bournesup** [comment]
it is not working on 5480. Could I email you the DSDT and help to create the suitable ACPI files?

**Comment by Baio1977** [comment]
[EFI Debug 0.7.5.zip](https://github.com/Baio1977/DELL-Inspiron-5584/files/7830975/EFI.Debug.0.7.5.zip)
Insert this in USB ,extract for me acpi your Dell

**Comment by bournesup** [comment]
[DSDT.zip](https://github.com/Baio1977/DELL-Inspiron-5584/files/7832736/DSDT.zip)
Will this work?

**Comment by Baio1977** [comment]
describe the HW features of your dell , contact me in telegram

**Comment by bournesup** [comment]
DELL Inspiron 5480: i5-8265u, 16GB, Samsung EVO 860 SATA 250GB, Intel UHD 620, ALC236, BCM94360NG, Realtek RTL8100.

**Comment by Baio1977** [comment]
[EFI.zip](https://github.com/Baio1977/DELL-Inspiron-5584/files/7836061/EFI.zip)
test this efi if start ioreg
