### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by kleiton** [Baio1977/DELL-Inspiron-5584#6]
Friend, I have the same notebook (dell 5584)

Despite working with IT I am a complete beginner with hackintosh, could you please tell me how I should proceed with these files that you have made available here in the repository?

I understand that I need to burn the OS on the pendrive, initialize and format the partition, is there any configuration required during the installation process, or are these files made available here only for configuration after installation?

Sorry for the beginner questions, but taking advantage of the fact that it's the same machine, I'm thinking of trying to perform this installation.

Thanks!

**Comment by Baio1977** [comment]
https://t.me/HackintoshLife_it
