### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by Samnan** [Baio1977/DELL-Inspiron-5584#7]
Hi @Baio1977 

   Just a quick question, hopefully you remember!
   Which commit in the repo was to update opencore before upgrading to MacOS Monterey. I cannot update this laptop to Monterey whenever I try, keeps restarting (Big sur works fine). Would be good to see your commit changes which made it work.
   Alternatively, maybe you remember the device that might cause Monterey upgrade to fail so I can check my DSDT.

   Thanks.

**Comment by Baio1977** [comment]
can you pass me efi + ioreg of big sur?

**Comment by Samnan** [comment]
Attached!
[bigsur.zip](https://github.com/Baio1977/DELL-Inspiron-5584/files/8788918/bigsur.zip)

**Comment by Baio1977** [comment]
[EFI.zip](https://github.com/Baio1977/DELL-Inspiron-5584/files/8789969/EFI.zip)
TEST this EFI in USB if start ioreg

**Comment by Samnan** [comment]
Cool, will test wheneven I can and report back.
Thanks

**Comment by Baio1977** [comment]
ioreg my efi please

**Comment by Samnan** [comment]
Unfortunately boot immediately crashes with multiple device errors.
I notice that almost all device definitions are different from my existing working configuration, so not very useful.

I will try working with my own oc setup further and try to debug the issue on what device causes the problem.

Thanks for the help anyway, appreciate it.
